(async()=>{
 const root=document.querySelector('#guidance');if(!root)return;const $=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 const tasks=[['simple_spread','MPE · Spread'],['simple_tag','MPE · Tag'],['simple_world','MPE · World'],['3m','SMAC · 3m'],['2s3z','SMAC · 2s3z'],['5m_vs_6m','SMAC · 5m vs 6m'],['8m','SMAC · 8m']];
 let lang='zh',mode='rollout',data=null,idx=0,t=0,last=0,playing=true,visible=false,ticket=0,cache={},cards=[],bounds=null;
 const tr=(a,b)=>lang==='zh'?a:b,gray='#9398a5',purple='#794ec8',clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),mix=(a,b,f)=>a+(b-a)*f;
 const rec=(branch,i=idx)=>data.branches[branch][Math.min(i,data.branches[branch].length-1)];
 function ctx(canvas){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle='#f9f8fc';c.fillRect(0,0,canvas.width,canvas.height);c.font='14px system-ui';c.textAlign='left';c.setLineDash([]);c.globalAlpha=1;return c}
 function dot(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()}
 function arrow(c,x,y,dx,dy,color,dash=false){c.strokeStyle=color;c.fillStyle=color;c.lineWidth=3;c.setLineDash(dash?[5,4]:[]);c.beginPath();c.moveTo(x,y);c.lineTo(x+dx,y+dy);c.stroke();c.setLineDash([]);if(Math.hypot(dx,dy)<1)return;const a=Math.atan2(dy,dx);c.beginPath();c.moveTo(x+dx,y+dy);c.lineTo(x+dx-8*Math.cos(a-.5),y+dy-8*Math.sin(a-.5));c.lineTo(x+dx-8*Math.cos(a+.5),y+dy-8*Math.sin(a+.5));c.closePath();c.fill()}
 function scene(canvas,branch){const c=ctx(canvas),w=canvas.width,h=canvas.height,d=rec(branch),f=idx>=data.branches[branch].length?1:clamp(t/.7,0,1),color=branch==='baseline'?gray:purple,sc=(Math.min(w,h)-80)/bounds.span,xy=p=>[w/2+(p.x-bounds.cx)*sc,h/2-(p.y-bounds.cy)*sc];
  if(data.domain==='MPE')d.state.landmarks.filter(l=>!l.boundary).forEach(p=>{const a=xy(p);if(data.task==='simple_spread'){c.strokeStyle='#b4aabd';c.lineWidth=2;c.beginPath();c.arc(...a,12,0,Math.PI*2);c.stroke()}else dot(c,...a,Math.max(4,p.radius*sc),'#d3d4dc')});
  for(let a=0;a<data.n_agents;a++){c.strokeStyle=color;c.lineWidth=2;c.globalAlpha=.65;c.setLineDash(branch==='baseline'?[5,4]:[]);c.beginPath();for(let j=0;j<=Math.min(idx,data.branches[branch].length-1);j++){const p=xy(rec(branch,j).state.agents[a]);j?c.lineTo(...p):c.moveTo(...p)}const p=d.state.agents[a],q=d.next_state.agents[a];c.lineTo(...xy({x:mix(p.x,q.x,f),y:mix(p.y,q.y,f)}));c.stroke();c.setLineDash([]);c.globalAlpha=1}
  for(const key of data.domain==='SMAC'?['agents','enemies']:['agents'])d.state[key].forEach((p,a)=>{const q=d.next_state[key][a],x=xy({x:mix(p.x,q.x,f),y:mix(p.y,q.y,f)}),col=key==='enemies'||a>=data.n_agents?'#d7777f':color;if(data.domain==='SMAC'&&mix(p.health,q.health,f)<=0)return;dot(c,...x,10,col);c.fillStyle='#fff';c.textAlign='center';c.fillText(key==='enemies'?'E'+(a+1):String(a+1),x[0],x[1]+5);if(data.domain==='SMAC'){c.fillStyle='#dfdbe6';c.fillRect(x[0]-15,x[1]-21,30,4);c.fillStyle=col;c.fillRect(x[0]-15,x[1]-21,30*clamp(mix(p.health,q.health,f)/p.max_health,0,1),4)}});
 }
 const actionName=i=>i===0?tr('空操作','No-op'):i===1?tr('停留','Stop'):i===2?tr('向北','North'):i===3?tr('向南','South'):i===4?tr('向东','East'):i===5?tr('向西','West'):tr('攻击 ','Attack ')+(i-5);
 function actionCard(canvas,d,a){const c=ctx(canvas),w=canvas.width,h=canvas.height;
  if(data.domain==='MPE'){const sc=75,x=w/2,y=h/2;c.strokeStyle='#ddd6e7';c.lineWidth=1;for(let off of [-1,0,1]){c.beginPath();c.moveTo(x+off*sc,20);c.lineTo(x+off*sc,h-20);c.stroke();c.beginPath();c.moveTo(20,y+off*sc);c.lineTo(w-20,y+off*sc);c.stroke()}arrow(c,x,y,d.proposal[a][0]*sc,-d.proposal[a][1]*sc,gray,true);arrow(c,x,y,d.refined[a][0]*sc,-d.refined[a][1]*sc,purple);dot(c,x,y,3,'#675776');c.fillStyle='#766881';c.font='11px system-ui';c.fillText('x',w-14,y-6);c.fillText('y',x+7,14);
  }else{const legal=d.legal[a].map((v,i)=>v?i:null).filter(i=>i!==null),dy=(h-18)/legal.length;c.font='11px system-ui';legal.forEach((i,j)=>{const y=8+j*dy;c.fillStyle='#716879';c.fillText(actionName(i),5,y+10);c.fillStyle=gray;c.fillRect(76,y,d.proposal[a][i]*(w-86),Math.min(5,dy/3));c.fillStyle=purple;c.fillRect(76,y+7,d.refined[a][i]*(w-86),Math.min(5,dy/3))})}
 }
 function render(){if(!data)return;const d=rec('guided'),limit=Math.max(data.branches.baseline.length,data.branches.guided.length),roll=mode==='rollout';$('[data-g-title]').textContent=tr('看清 Q 值引导改变了什么。','See what Q guidance changes.');$('[data-g-lang]').textContent=lang==='zh'?'English':'中文';$('[data-g-intro]').textContent=tr('同一起点、同一策略与配对随机种子。灰色直接执行原始提案，紫色先做一次 Q 梯度微调，再交给仿真环境执行。','Same starting state, policy and paired random seeds. Gray executes the original proposal; purple applies one Q-gradient refinement before simulator execution.');
 all('[data-g-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.gMode===mode);b.setAttribute('aria-pressed',String(b.dataset.gMode===mode));b.textContent=b.dataset.gMode==='rollout'?tr('轨迹对照','Trajectory comparison'):tr('动作调整','Action refinement')});$('[data-g-meta]').textContent='Medium · η = '+data.eta+' · K = '+data.denoising_steps;
 $('[data-g-before]').textContent=tr('未引导','Unrefined');$('[data-g-after]').textContent=tr('Q 值引导后','Q-guided');$('[data-g-step]').textContent=tr('决策 ','Decision ')+(idx+1)+' / '+limit;$('[data-g-baseline-title]').textContent=tr('未引导 · 实际执行轨迹','Unrefined · simulator trajectory')+(idx>=data.branches.baseline.length?tr('（已结束）',' (ended)'):'');$('[data-g-guided-title]').textContent=tr('Q 值引导后 · 实际执行轨迹','Q-guided · simulator trajectory')+(idx>=data.branches.guided.length?tr('（已结束）',' (ended)'):'');
 $('[data-g-rollout]').hidden=!roll;$('[data-g-actions]').hidden=roll;if(roll){scene($('[data-g-baseline]'),'baseline');scene($('[data-g-guided]'),'guided')}else cards.forEach((o,a)=>{o.title.textContent=tr('智能体 ','Agent ')+(a+1);actionCard(o.canvas,d,a);if(data.domain==='MPE'){o.note.textContent='('+d.proposal[a].map(x=>x.toFixed(3)).join(', ')+') → ('+d.refined[a].map(x=>x.toFixed(3)).join(', ')+')'}else{o.note.textContent=actionName(d.proposal_action[a])+' → '+actionName(d.refined_action[a])+(d.proposal_action[a]===d.refined_action[a]?tr('（动作未变）',' (unchanged)'):'')}});
 $('[data-g-explanation]').textContent=roll?tr('两边从完全相同的初始状态出发；每一步分别按各自状态决策，因此后续提案也可能不同。位置来自实际仿真，线条连接已执行的轨迹点。','Both branches start in the same verified state. Each then acts on its own state, so later proposals may differ. Positions are recorded simulator states; lines connect executed positions.'):data.domain==='MPE'?tr('这里比较引导分支的同一次提案：灰色箭头为原始动作，紫色箭头为调整后动作。箭头是动作向量，不是未来位置。','Compare one proposal in the guided branch: gray is the original action and purple is the refined action. Arrows represent actions, not future positions.'):tr('灰/紫条分别表示调整前后的合法动作 softmax 权重；下方显示最终选择。权重改变时，最终动作也可能不变。','Gray/purple bars show legal-action softmax weights before/after refinement. The final choice is below; changed weights need not change the selected action.');
 $('[data-g-q-label]').textContent=data.domain==='SMAC'?tr('Softmax 动作的 Q 估计','Q estimates of softmax actions'):tr('同一次提案的 Q 估计','Q estimates for the same proposal');$('[data-g-q]').textContent=d.q_before.toFixed(2)+' → '+d.q_after.toFixed(2);$('[data-g-q-note]').textContent=tr('取当前引导分支的同一观测；不等于实际回报。','Same observation in the guided branch; not a realized return.');const returns=['baseline','guided'].map(b=>data.branches[b].slice(0,idx+1).reduce((s,r)=>s+r.reward,0));$('[data-g-return-label]').textContent=tr('实际片段累计回报：未引导 / 引导后','Recorded segment return: unrefined / guided');$('[data-g-return]').textContent=returns.map(x=>x.toFixed(2)).join(' / ');$('[data-g-return-note]').textContent=tr('各智能体原始奖励求和；不是整局结果或平均成绩。','Sum of raw agent rewards; not a full episode or aggregate score.');
 $('[data-g-play]').textContent=playing?tr('暂停','Pause'):tr('播放','Play');$('[data-g-replay]').textContent=tr('从头播放','Restart');$('[data-g-next]').textContent=tr('下一步 →','Next →');$('[data-g-slider]').value=idx;$('[data-g-protocol]').textContent=tr('真实模型与仿真输出 · seed 10000 · 已有 Medium 检查点 · 每步一次全局归一化 Q 梯度调整。所有连续记录均保留，动画仅在真实状态之间插值。','Recorded model and simulator outputs · seed 10000 · existing Medium checkpoints · one globally normalized Q-gradient update per step. Every consecutive record is retained; playback only interpolates recorded states.');
 $('[data-g-detail-title]').textContent=tr('比较方式与原始数据','Comparison protocol and raw data');$('[data-g-detail]').textContent=tr('这不是世界模型预测。两分支仅在初始状态共享完全相同的观测与策略提案，后续状态各自演化。动作卡与 Q 值始终在引导分支同一观测下比较。短片段可出现持平或下降，不能据此推断总体收益；SMAC 图为位置/血量示意回放，不是游戏客户端录像。','These are not world-model predictions. Both branches share the exact initial observation and proposal, then evolve separately. Action cards and Q estimates always compare the same observation within the guided branch. A short segment can tie or regress and does not establish aggregate benefit. SMAC panels are position/health schematics, not client footage.');
 }
 async function load(id){const n=++ticket;data=null;playing=false;$('[data-g-player]').hidden=true;$('[data-g-status]').hidden=false;$('[data-g-status]').textContent=tr('正在载入真实模型输出…','Loading recorded model outputs…');all('[data-g-task]').forEach(b=>{b.classList.toggle('active',b.dataset.gTask===id);b.setAttribute('aria-pressed',String(b.dataset.gTask===id))});try{const d=cache[id]||await fetch('assets/guidance/'+id+'.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()});if(n!==ticket)return;cache[id]=d;data=d;idx=0;t=0;last=0;playing=mode==='rollout';const points=Object.values(d.branches).flat().flatMap(r=>[r.state,r.next_state]).flatMap(s=>[...s.agents,...(s.enemies||[]),...(s.landmarks||[]).filter(x=>!x.boundary)]),xs=points.map(p=>p.x),ys=points.map(p=>p.y);bounds={cx:(Math.min(...xs)+Math.max(...xs))/2,cy:(Math.min(...ys)+Math.max(...ys))/2,span:Math.max(data.domain==='SMAC'?10:2.5,Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys))*1.15};cards=[];$('[data-g-actions]').replaceChildren();for(let a=0;a<d.n_agents;a++){let box=document.createElement('article');box.innerHTML='<h3></h3><canvas width="240" height="200"></canvas><p></p>';$('[data-g-actions]').appendChild(box);cards.push({title:box.querySelector('h3'),canvas:box.querySelector('canvas'),note:box.querySelector('p')})}$('[data-g-slider]').max=Math.max(d.branches.baseline.length,d.branches.guided.length)-1;$('[data-g-download]').href='assets/guidance/'+id+'.json';$('[data-g-player]').hidden=false;$('[data-g-status]').hidden=true;render()}catch(e){if(n!==ticket)return;$('[data-g-status]').textContent=tr('加载失败，请重新点击任务。','Could not load this task. Click to retry.');console.error(e)}}
 for(const [id,label]of tasks){const b=document.createElement('button');b.dataset.gTask=id;b.textContent=label;b.addEventListener('click',()=>load(id));$('[data-g-tasks]').appendChild(b)}
 all('[data-g-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.gMode;t=0;playing=mode==='rollout';render()}));$('[data-g-lang]').addEventListener('click',()=>{lang=lang==='zh'?'en':'zh';render()});$('[data-g-play]').addEventListener('click',()=>{playing=!playing;last=0;render()});$('[data-g-replay]').addEventListener('click',()=>{idx=0;t=0;playing=true;render()});$('[data-g-next]').addEventListener('click',()=>{if(data){idx=(idx+1)%Math.max(data.branches.baseline.length,data.branches.guided.length);t=0;render()}});$('[data-g-slider]').addEventListener('input',e=>{idx=Number(e.target.value);t=0;render()});new IntersectionObserver(es=>{visible=es[0].isIntersecting;last=0},{threshold:.05}).observe(root);
 function tick(now){if(data&&playing&&visible&&!document.hidden&&last){t+=Math.min((now-last)/1000,.1);if(t>(mode==='rollout'?.7:1.8)){t=0;idx=(idx+1)%Math.max(data.branches.baseline.length,data.branches.guided.length)}render()}last=now;requestAnimationFrame(tick)}requestAnimationFrame(tick);await load('simple_spread');
})();
