(async()=>{
 const root=document.querySelector('#guidance');if(!root)return;const $=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 const tasks=[['simple_spread','MPE · Spread'],['simple_tag','MPE · Tag'],['simple_world','MPE · World'],['3m','SMAC · 3m'],['2s3z','SMAC · 2s3z'],['5m_vs_6m','SMAC · 5m vs 6m'],['8m','SMAC · 8m']];
 let selected=0,agentButtons=[];let lang='zh',mode='rollout',data=null,idx=0,t=0,last=0,playing=true,visible=false,ticket=0,cache={},cards=[],bounds=null;
 const tr=(a,b)=>lang==='zh'?a:b,gray='#9398a5',purple='#794ec8',clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),mix=(a,b,f)=>a+(b-a)*f;
 const rec=(branch,i=idx)=>data.branches[branch][Math.min(i,data.branches[branch].length-1)];
 function ctx(canvas){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle='#f9f8fc';c.fillRect(0,0,canvas.width,canvas.height);c.font='14px system-ui';c.textAlign='left';c.setLineDash([]);c.globalAlpha=1;return c}
 function dot(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()}
 function arrow(c,x,y,dx,dy,color,dash=false){c.strokeStyle=color;c.fillStyle=color;c.lineWidth=3;c.setLineDash(dash?[5,4]:[]);c.beginPath();c.moveTo(x,y);c.lineTo(x+dx,y+dy);c.stroke();c.setLineDash([]);if(Math.hypot(dx,dy)<1)return;const a=Math.atan2(dy,dx);c.beginPath();c.moveTo(x+dx,y+dy);c.lineTo(x+dx-8*Math.cos(a-.5),y+dy-8*Math.sin(a-.5));c.lineTo(x+dx-8*Math.cos(a+.5),y+dy-8*Math.sin(a+.5));c.closePath();c.fill()}
 function scene(canvas,branch){const c=ctx(canvas),w=canvas.width,h=canvas.height,d=rec(branch),f=idx>=data.branches[branch].length?1:clamp(t/.7,0,1),color=branch==='baseline'?gray:purple,sc=(Math.min(w,h)-80)/bounds.span,xy=p=>[w/2+(p.x-bounds.cx)*sc,h/2-(p.y-bounds.cy)*sc];
  if(data.domain==='MPE')d.state.landmarks.filter(l=>!l.boundary).forEach(p=>{const a=xy(p);if(data.task==='simple_spread'){c.strokeStyle='#b4aabd';c.lineWidth=2;c.beginPath();c.arc(...a,12,0,Math.PI*2);c.stroke()}else dot(c,...a,Math.max(4,p.radius*sc),'#d3d4dc')});
  for(let a=0;a<data.n_agents;a++){c.strokeStyle=color;c.lineWidth=2;c.globalAlpha=.65;c.setLineDash(branch==='baseline'?[5,4]:[]);c.beginPath();for(let j=0;j<=Math.min(idx,data.branches[branch].length-1);j++){const p=xy(rec(branch,j).state.agents[a]);j?c.lineTo(...p):c.moveTo(...p)}const p=d.state.agents[a],q=d.next_state.agents[a];c.lineTo(...xy({x:mix(p.x,q.x,f),y:mix(p.y,q.y,f)}));c.stroke();c.setLineDash([]);c.globalAlpha=1}
  for(const key of data.domain==='SMAC'?['agents','enemies']:['agents'])d.state[key].forEach((p,a)=>{const q=d.next_state[key][a],x=xy({x:mix(p.x,q.x,f),y:mix(p.y,q.y,f)}),col=key==='enemies'||a>=data.n_agents?'#d7777f':color;if(data.domain==='SMAC'&&mix(p.health,q.health,f)<=0)return;dot(c,...x,10,col);c.fillStyle='#fff';c.textAlign='center';c.fillText(key==='enemies'?'E'+(a+1):String(a+1),x[0],x[1]+5);if(data.domain==='SMAC'){c.fillStyle='#dfdbe6';c.fillRect(x[0]-15,x[1]-21,30,4);c.fillStyle=col;c.fillRect(x[0]-15,x[1]-21,30*clamp(mix(p.health,q.health,f)/p.max_health,0,1),4)}});
 }
 const actionName=i=>i===0?tr('空操作','No-op'):i===1?tr('停留','Stop'):i===2?tr('向北','North'):i===3?tr('向南','South'):i===4?tr('向东','East'):i===5?tr('向西','West'):tr('攻击 ','Attack ')+(i-5);
 function actionCard(canvas,d,a){const c=ctx(canvas),w=canvas.width,h=canvas.height;
  if(data.domain==='MPE'){const sc=75,x=w/2,y=h/2;c.strokeStyle='#ddd6e7';c.lineWidth=1;for(let off of [-1,0,1]){c.beginPath();c.moveTo(x+off*sc,20);c.lineTo(x+off*sc,h-20);c.stroke();c.beginPath();c.moveTo(20,y+off*sc);c.lineTo(w-20,y+off*sc);c.stroke()}arrow(c,x,y,d.proposal[a][0]*sc,-d.proposal[a][1]*sc,gray,true);arrow(c,x,y,d.refined[a][0]*sc,-d.refined[a][1]*sc,purple);dot(c,x,y,3,'#675776');c.fillStyle='#766881';c.font='11px system-ui';c.fillText('x',w-14,y-6);c.fillText('y',x+7,14);
  }else{const legal=d.legal[a].map((v,i)=>v?i:null).filter(i=>i!==null),dy=(h-18)/legal.length;c.font='11px system-ui';legal.forEach((i,j)=>{const y=8+j*dy;c.fillStyle='#716879';c.fillText(actionName(i),5,y+10);c.fillStyle=gray;c.fillRect(76,y,d.proposal[a][i]*(w-86),Math.min(5,dy/3));c.fillStyle=purple;c.fillRect(76,y+7,d.refined[a][i]*(w-86),Math.min(5,dy/3))})}
 }

 const magnitude=(d,a)=>data.domain==='SMAC'?Number(d.proposal_action[a]!==d.refined_action[a]):Math.hypot(...d.proposal[a].map((v,j)=>d.refined[a][j]-v));
 function focus(){
  const d=rec('guided'),a=selected,change=magnitude(d,a),ended=idx>=data.branches.guided.length;
  $('[data-g-focus-title]').textContent=tr('先看这一处变化','Start with this change');$('[data-g-jump]').textContent=tr('下一处动作变化 →','Next changed action →');
  $('[data-g-event]').textContent=tr('第 ','Decision ')+(idx+1)+tr(' 步 · 智能体 ',' · Agent ')+(a+1)+' · '+(ended?tr('引导分支已结束','Guided branch ended'):data.domain==='SMAC'?actionName(d.proposal_action[a])+' → '+actionName(d.refined_action[a])+(change?'':tr('（最终动作未变）',' (same selected action)')):tr('动作调整幅度 ','Action adjustment magnitude ')+change.toFixed(3));
  agentButtons.forEach((b,i)=>{b.textContent=tr('智能体 ','Agent ')+(i+1)+(magnitude(d,i)>1e-6?' ●':'');b.classList.toggle('active',i===a);b.setAttribute('aria-pressed',String(i===a))});
  $('[data-g-decision-title]').textContent=tr('① 同一状态：动作怎样改了？','① Same state: what changed?');$('[data-g-overlay-title]').textContent=tr('② 实际执行：轨迹叠在一起看','② Execution: overlay both trajectories');
  const canvas=$('[data-g-decision]'),c=ctx(canvas),w=canvas.width,h=canvas.height,scale=(Math.min(w,h)-80)/bounds.span,xy=p=>[w/2+(p.x-bounds.cx)*scale,h/2-(p.y-bounds.cy)*scale];
  const units=(cc,state,map,color)=>{state.agents.forEach((p,i)=>{if(data.domain==='SMAC'&&p.health<=0)return;const z=map(p);dot(cc,...z,i===a?13:7,i<data.n_agents?color:'#d7777f');cc.fillStyle='#342542';cc.textAlign='center';cc.fillText(String(i+1),z[0],z[1]-16)});(state.enemies||[]).forEach((p,i)=>{if(p.health<=0)return;const z=map(p);dot(cc,...z,9,'#d7777f');cc.fillStyle='#9b3743';cc.fillText('E'+(i+1),z[0],z[1]-15)});(state.landmarks||[]).filter(p=>!p.boundary).forEach(p=>{const z=map(p);cc.strokeStyle='#b9b0c7';cc.beginPath();cc.arc(...z,Math.max(5,(p.radius||.05)*scale),0,Math.PI*2);cc.stroke()})};
  units(c,d.state,xy,purple);const origin=xy(d.state.agents[a]);
  function drawAction(action,color,dash){if(data.domain==='MPE'){arrow(c,...origin,action[0]*65,-action[1]*65,color,dash);return}if(action>=6){const enemy=d.state.enemies[action-6];if(enemy){const z=xy(enemy);arrow(c,...origin,z[0]-origin[0],z[1]-origin[1],color,dash)}}else if(action>=2){const dirs={2:[0,-50],3:[0,50],4:[50,0],5:[-50,0]};arrow(c,...origin,...dirs[action],color,dash)}else{c.strokeStyle=color;c.setLineDash(dash?[5,4]:[]);c.beginPath();c.arc(...origin,dash?22:17,0,Math.PI*2);c.stroke();c.setLineDash([])}}
  drawAction(d.proposal_action[a],gray,true);drawAction(d.refined_action[a],purple,false);
  $('[data-g-decision-note]').textContent=tr('灰虚线＝原动作；紫实线＝调整后。● 表示该智能体本步动作改变。','Dashed gray = original; solid purple = refined. ● marks an agent whose action changed.')+' '+(data.domain==='MPE'?tr('箭头是动作方向，长度使用固定比例，不是预测位移。','Arrows show actions at a fixed scale, not predicted displacement.'):tr('连线指向攻击目标；短箭头表示移动方向，圆环表示停留/空操作。','Lines identify attack targets; short arrows show movement; rings indicate stop/no-op.'));
  const cv=$('[data-g-overlay]'),cc=ctx(cv);let endpoints=[];
  for(const [branch,color] of [['baseline',gray],['guided',purple]]){const list=data.branches[branch],end=Math.min(idx,list.length-1);cc.strokeStyle=color;cc.lineWidth=4;cc.setLineDash(branch==='baseline'?[7,5]:[]);cc.beginPath();for(let j=0;j<=end;j++){const z=xy(list[j].state.agents[a]);j?cc.lineTo(...z):cc.moveTo(...z)}const point=list[end].next_state.agents[a],z=xy(point);cc.lineTo(...z);cc.stroke();cc.setLineDash([]);dot(cc,...z,branch==='baseline'?11:7,color);endpoints.push(point)}
  const start=xy(data.branches.guided[0].state.agents[a]);dot(cc,...start,5,'#403748');cc.fillStyle='#403748';cc.textAlign='left';cc.fillText(tr('共同起点','Shared start'),start[0]+9,start[1]-10);
  const gap=Math.hypot(endpoints[0].x-endpoints[1].x,endpoints[0].y-endpoints[1].y);let outcome=tr('本步执行后，两分支位置相距 ','After this step, branch positions differ by ')+gap.toFixed(3)+tr(' 环境单位。',' environment units.');
  if(data.domain==='SMAC'){const values=['baseline','guided'].map(b=>{const st=rec(b).next_state;return st.agents.filter(p=>p.health>0).length+'/'+data.n_agents+' · '+st.enemies.reduce((n,p)=>n+p.health+p.shield,0).toFixed(0)});outcome+=' '+tr('己方存活 / 总数 · 敌方剩余血量与护盾：灰 ','Allies alive / total · enemy health + shields: gray ')+values[0]+tr('；紫 ','; purple ')+values[1]}
  $('[data-g-outcome]').textContent=outcome;
  const n=data.branches.guided.filter(r=>r.proposal_action.some((_,i)=>magnitude(r,i)>1e-6)).length,returns=['baseline','guided'].map(b=>data.branches[b].reduce((v,r)=>v+r.reward,0));
  $('[data-g-summary]').textContent=tr('整段记录：','Whole recorded segment: ')+n+'/'+data.branches.guided.length+tr(' 步改变了至少一个动作；原始片段回报：未引导 ',' decisions changed at least one action; raw segment return: unrefined ')+returns[0].toFixed(2)+tr(' → 引导后 ',' → guided ')+returns[1].toFixed(2)+tr('。此处解释机制，论文总体效果请看下方实验结果。','. This view explains the mechanism; see the experiments below for overall performance.');
  $('[data-g-evidence]').textContent=tr('查看论文实验结果 ↓','See paper results ↓');
 }
 function render(){if(!data)return;focus();const d=rec('guided'),limit=Math.max(data.branches.baseline.length,data.branches.guided.length),roll=mode==='rollout';$('[data-g-title]').textContent=tr('看清 Q 值引导改变了什么。','See what Q guidance changes.');$('[data-g-lang]').textContent=lang==='zh'?'English':'中文';$('[data-g-intro]').textContent=tr('同一起点、同一策略与配对随机种子。灰色直接执行原始提案，紫色先做一次 Q 梯度微调，再交给仿真环境执行。','Same starting state, policy and paired random seeds. Gray executes the original proposal; purple applies one Q-gradient refinement before simulator execution.');
 all('[data-g-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.gMode===mode);b.setAttribute('aria-pressed',String(b.dataset.gMode===mode));b.textContent=b.dataset.gMode==='rollout'?tr('轨迹对照','Trajectory comparison'):tr('动作调整','Action refinement')});$('[data-g-meta]').textContent='Medium · η = '+data.eta+' · K = '+data.denoising_steps;
 $('[data-g-before]').textContent=tr('未引导','Unrefined');$('[data-g-after]').textContent=tr('Q 值引导后','Q-guided');$('[data-g-step]').textContent=tr('决策 ','Decision ')+(idx+1)+' / '+limit;$('[data-g-baseline-title]').textContent=tr('未引导 · 实际执行轨迹','Unrefined · simulator trajectory')+(idx>=data.branches.baseline.length?tr('（已结束）',' (ended)'):'');$('[data-g-guided-title]').textContent=tr('Q 值引导后 · 实际执行轨迹','Q-guided · simulator trajectory')+(idx>=data.branches.guided.length?tr('（已结束）',' (ended)'):'');
 $('[data-g-rollout]').hidden=!roll;$('[data-g-actions]').hidden=roll;if(roll){scene($('[data-g-baseline]'),'baseline');scene($('[data-g-guided]'),'guided')}else cards.forEach((o,a)=>{o.title.textContent=tr('智能体 ','Agent ')+(a+1);actionCard(o.canvas,d,a);if(data.domain==='MPE'){o.note.textContent='('+d.proposal[a].map(x=>x.toFixed(3)).join(', ')+') → ('+d.refined[a].map(x=>x.toFixed(3)).join(', ')+')'}else{o.note.textContent=actionName(d.proposal_action[a])+' → '+actionName(d.refined_action[a])+(d.proposal_action[a]===d.refined_action[a]?tr('（动作未变）',' (unchanged)'):'')}});
 $('[data-g-explanation]').textContent=roll?tr('两边从完全相同的初始状态出发；每一步分别按各自状态决策，因此后续提案也可能不同。位置来自实际仿真，线条连接已执行的轨迹点。','Both branches start in the same verified state. Each then acts on its own state, so later proposals may differ. Positions are recorded simulator states; lines connect executed positions.'):data.domain==='MPE'?tr('这里比较引导分支的同一次提案：灰色箭头为原始动作，紫色箭头为调整后动作。箭头是动作向量，不是未来位置。','Compare one proposal in the guided branch: gray is the original action and purple is the refined action. Arrows represent actions, not future positions.'):tr('灰/紫条分别表示调整前后的合法动作 softmax 权重；下方显示最终选择。权重改变时，最终动作也可能不变。','Gray/purple bars show legal-action softmax weights before/after refinement. The final choice is below; changed weights need not change the selected action.');
 $('[data-g-q-label]').textContent=data.domain==='SMAC'?tr('Softmax 动作的 Q 估计','Q estimates of softmax actions'):tr('同一次提案的 Q 估计','Q estimates for the same proposal');$('[data-g-q]').textContent=d.q_before.toFixed(2)+' → '+d.q_after.toFixed(2);$('[data-g-q-note]').textContent=tr('取当前引导分支的同一观测；不等于实际回报。','Same observation in the guided branch; not a realized return.');const returns=['baseline','guided'].map(b=>data.branches[b].slice(0,idx+1).reduce((s,r)=>s+r.reward,0));$('[data-g-return-label]').textContent=tr('实际片段累计回报：未引导 / 引导后','Recorded segment return: unrefined / guided');$('[data-g-return]').textContent=returns.map(x=>x.toFixed(2)).join(' / ');$('[data-g-return-note]').textContent=tr('各智能体原始奖励求和；不是整局结果或平均成绩。','Sum of raw agent rewards; not a full episode or aggregate score.');
 $('[data-g-play]').textContent=playing?tr('暂停','Pause'):tr('播放','Play');$('[data-g-replay]').textContent=tr('从头播放','Restart');$('[data-g-next]').textContent=tr('下一步 →','Next →');$('[data-g-slider]').value=idx;$('[data-g-protocol]').textContent=tr('真实模型与仿真输出 · seed 10000 · 已有 Medium 检查点 · 每步一次全局归一化 Q 梯度调整。所有连续记录均保留，动画仅在真实状态之间插值。','Recorded model and simulator outputs · seed 10000 · existing Medium checkpoints · one globally normalized Q-gradient update per step. Every consecutive record is retained; playback only interpolates recorded states.');
 $('[data-g-detail-title]').textContent=tr('比较方式与原始数据','Comparison protocol and raw data');$('[data-g-detail]').textContent=tr('这不是世界模型预测。两分支仅在初始状态共享完全相同的观测与策略提案，后续状态各自演化。动作卡与 Q 值始终在引导分支同一观测下比较。短片段可出现持平或下降，不能据此推断总体收益；SMAC 图为位置/血量示意回放，不是游戏客户端录像。','These are not world-model predictions. Both branches share the exact initial observation and proposal, then evolve separately. Action cards and Q estimates always compare the same observation within the guided branch. A short segment can tie or regress and does not establish aggregate benefit. SMAC panels are position/health schematics, not client footage.');
 }
 async function load(id){const n=++ticket;data=null;playing=false;$('[data-g-player]').hidden=true;$('[data-g-status]').hidden=false;$('[data-g-status]').textContent=tr('正在载入真实模型输出…','Loading recorded model outputs…');all('[data-g-task]').forEach(b=>{b.classList.toggle('active',b.dataset.gTask===id);b.setAttribute('aria-pressed',String(b.dataset.gTask===id))});try{const d=cache[id]||await fetch('assets/guidance/'+id+'.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()});if(n!==ticket)return;cache[id]=d;data=d;selected=0;agentButtons=[];$('[data-g-agents]').replaceChildren();for(let a=0;a<d.n_agents;a++){const b=document.createElement('button');b.addEventListener('click',()=>{selected=a;playing=false;t=0;render()});$('[data-g-agents]').appendChild(b);agentButtons.push(b)}idx=0;t=0;last=0;playing=mode==='rollout';const points=Object.values(d.branches).flat().flatMap(r=>[r.state,r.next_state]).flatMap(s=>[...s.agents,...(s.enemies||[]),...(s.landmarks||[]).filter(x=>!x.boundary)]),xs=points.map(p=>p.x),ys=points.map(p=>p.y);bounds={cx:(Math.min(...xs)+Math.max(...xs))/2,cy:(Math.min(...ys)+Math.max(...ys))/2,span:Math.max(data.domain==='SMAC'?10:2.5,Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys))*1.15};cards=[];$('[data-g-actions]').replaceChildren();for(let a=0;a<d.n_agents;a++){let box=document.createElement('article');box.innerHTML='<h3></h3><canvas width="240" height="200"></canvas><p></p>';$('[data-g-actions]').appendChild(box);cards.push({title:box.querySelector('h3'),canvas:box.querySelector('canvas'),note:box.querySelector('p')})}$('[data-g-slider]').max=Math.max(d.branches.baseline.length,d.branches.guided.length)-1;$('[data-g-download]').href='assets/guidance/'+id+'.json';$('[data-g-player]').hidden=false;$('[data-g-status]').hidden=true;render()}catch(e){if(n!==ticket)return;$('[data-g-status]').textContent=tr('加载失败，请重新点击任务。','Could not load this task. Click to retry.');console.error(e)}}
 $('[data-g-jump]').addEventListener('click',()=>{if(!data)return;const list=data.branches.guided;for(let off=1;off<=list.length;off++){const j=(idx+off)%list.length;const a=list[j].proposal_action.findIndex((_,i)=>magnitude(list[j],i)>1e-6);if(a>=0){idx=j;selected=a;t=0;playing=false;render();return}}});
 for(const [id,label]of tasks){const b=document.createElement('button');b.dataset.gTask=id;b.textContent=label;b.addEventListener('click',()=>load(id));$('[data-g-tasks]').appendChild(b)}
 all('[data-g-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.gMode;t=0;playing=mode==='rollout';render()}));$('[data-g-lang]').addEventListener('click',()=>{lang=lang==='zh'?'en':'zh';render()});$('[data-g-play]').addEventListener('click',()=>{playing=!playing;last=0;render()});$('[data-g-replay]').addEventListener('click',()=>{idx=0;t=0;playing=true;render()});$('[data-g-next]').addEventListener('click',()=>{if(data){idx=(idx+1)%Math.max(data.branches.baseline.length,data.branches.guided.length);t=0;render()}});$('[data-g-slider]').addEventListener('input',e=>{idx=Number(e.target.value);t=0;render()});new IntersectionObserver(es=>{visible=es[0].isIntersecting;last=0},{threshold:.05}).observe(root);
 function tick(now){if(data&&playing&&visible&&!document.hidden&&last){t+=Math.min((now-last)/1000,.1);if(t>(mode==='rollout'?.7:1.8)){t=0;idx=(idx+1)%Math.max(data.branches.baseline.length,data.branches.guided.length)}render()}last=now;requestAnimationFrame(tick)}requestAnimationFrame(tick);await load('simple_spread');
})();
